name: CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 1 * *' # Run on the first day of every month at 06:00 UTC

jobs:
  build_linux_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install libcgal-dev libboost-all-dev libeigen3-dev libomp-dev libgdal-dev
      - name: Build
        run: |
            mkdir build && cd build
            cmake .. && make -j4

  build_linux_2004:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install libcgal-dev libboost-all-dev libeigen3-dev libomp-dev libgdal-dev
      - name: Build
        run: |
            mkdir build && cd build
            cmake .. && make -j4

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
            brew update
            brew upgrade || true
            brew install cmake boost cgal eigen libomp gdal
      - name: Build
        run: |
            mkdir build && cd build
            cmake .. && make -j4

  build_win64:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKG_INSTALLATION_ROOT: C:\vcpkg
      VCPKG_FEATURE_FLAGS: manifests
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        vcpkg install
        mkdir Release
        cd Release
        cmake .. -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_INSTALL_PREFIX=C:\Software -DCMAKE_PREFIX_PATH=Release\vcpkg_installed\x64-windows\share\lastools
        cmake --build . --parallel 4 --config Release

  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker registry login
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      - name: Build the Docker image
        run: docker build --build-arg JOBS=2 . --file docker/city4cfd.dockerfile --tag tudelft3d/city4cfd:latest
