# This is a basic workflow to help you get started with Actions

name: Release Windows Executable

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [created]
  pull_request:    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release_win64:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKG_INSTALLATION_ROOT: C:\vcpkg
      VCPKG_FEATURE_FLAGS: manifests
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        vcpkg install
        mkdir Release
        cd Release
        cmake .. -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_INSTALL_PREFIX=C:\Software -DCMAKE_PREFIX_PATH=Release\vcpkg_installed\x64-windows\share\lastools
        cmake --build . --parallel 4 --config Release
    - name: Package binary files
      run: |
        7z a city4cfd-win64.zip .\Release\*
    - name: Upload binary files as artifact
      uses: actions/upload-artifact@master
      with:
        name: city4cfd-win64
        path: city4cfd-win64.zip
    - name: Add binaries as an asset to the release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          city4cfd-win64.zip

